In [ ]:
#1

In [ ]:
import numpy as np

In [12]:
# Use array() with nested brackets:
X = np.array([[25, 150], [61,1], [2, 3]])
X

array([[ 25, 150],
       [ 61,   1],
       [  2,   3]])

In [13]:
X.size

6

In [14]:
X[:,0]

array([25, 61,  2])

In [15]:
X[1,:]

array([61,  1])

In [ ]:
#2

In [16]:
import torch

In [17]:
X_pt = torch.tensor([[25, 150], [61, 1], [2, 3]])
X_pt

tensor([[ 25, 150],
        [ 61,   1],
        [  2,   3]])

In [22]:
X_pt.shape

torch.Size([3, 2])

In [20]:
X_pt[1,:]

tensor([61,  1])

In [23]:
import tensorflow as tf

In [24]:
X_tf = tf.Variable([[25, 150], [61, 1], [2, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 25, 150],
       [ 61,   1],
       [  2,   3]], dtype=int32)>

In [26]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [27]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([61,  1], dtype=int32)>