### Vectors (Rank 1 Tensors) in NumPy

In [ ]:
#Vector

In [1]:
#1
import numpy as np

In [23]:
x = np.array([11, 2, 3]) # type argument is optional, e.g.: dtype=np.float16
x

array([11,  2,  3])

In [24]:
len(x)

3

In [25]:
x.shape

(3,)

In [6]:
type(x)

numpy.ndarray

In [5]:
x[0] # zero-indexed

np.int64(11)

In [9]:
type(x[0])

numpy.int64

In [ ]:
#2

In [10]:
x_t = x.T
x_t

array([11,  2,  3])

In [27]:
x_t.shape

(3,)

In [14]:
y = np.array([[11, 2, 3]])
y

array([[11,  2,  3]])

In [15]:
y.shape

(1, 3)

In [ ]:
#3

In [29]:
import torch
import tensorflow as tf


In [30]:
x_pt = torch.tensor([11, 2, 3])
x_pt

tensor([11,  2,  3])

In [31]:
x_tf = tf.Variable([11, 2, 3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([11,  2,  3], dtype=int32)>