In [ ]:
#1

In [3]:
import numpy as np

In [4]:
i = np.array([1, 0])
i

array([1, 0])

In [5]:
j = np.array([0, 1])
j

array([0, 1])

In [6]:
np.dot(i, j)

np.int64(0)

In [ ]:
#2

In [10]:
v = np.array([1, 2])
v

array([1, 2])

In [8]:
w = np.array([2, -1])
w

array([ 2, -1])

In [11]:
np.dot(v, w)

np.int64(0)